### PR TITLE
added-mark-for -conntrack

### PR DESCRIPTION
**Pull request by sibicramesh**
Added parsing mark attribute for conntrack based on protocol.

### CODE REVIEW

**Comment by vishvananda** [comment]
Hi. Thanks for this update. You have some formatting errors in your code. Can you run go fmt, amend your commit and repush? Thanks

**Comment by sibicramesh** [comment]
Thanks for checking my PR. I have removed the fmt errors.

**Comment by vishvananda** [comment]
thank you. Could you also squash the two changes into a single commit? I prefer to have the history free of errors.

**Comment by sibicramesh** [comment]
Merged the commits. You can check it out. Thanks

**Pull request merged**
