### PR TITLE
Allow link argument to AddrAdd, AddReplace and AddrDel to be nil

### PR DESCRIPTION
**Pull request by cwmos**
This to address https://github.com/vishvananda/netlink/issues/947

### CODE REVIEW

**Comment by jellonek** [comment]
lgtm

**Comment by jellonek** [comment]
@aboch, @vishvananda  can you take a look? imo this change is clean and simple.

**Comment by aboch** [comment]
Thank you @cwmos and @jellonek 
Would it be possible to add a UT function for this?
Programming and then reading from kernel an address where the link parameter is nil, if not there yet.

**Comment by jellonek** [comment]
imo it is in the same bucket as checking if user provided non nil `addr`. we are not checking that what leads to panic, because developer calling this function did a horrible mistake.
UT would be nice to have, but imo is not needed. (i would merge that on your place :P )

**Comment by aboch** [comment]
If you do not want to add the ut to cover the following two lines
```
	if link == nil {
		msg.Index = uint32(addr.LinkIndex)
```
then I have to do it myself.
Believe me, it is going to take longer than one of you guys doing it.
Please add it.

**Comment by cwmos** [comment]
I agree a unit test is in place here - I don't want this use case to break in the future :-)

I will try to add one.

**Comment by aboch** [comment]
Thank you @cwmos 
Please squash your two commits into one.
This project follows a "one commit per feature/fix/enhancement" approach

**Comment by cwmos** [comment]
Done @aboch

**Comment by aboch** [comment]
LGTM

**Pull request merged**
