### PR TITLE
Add RouteReplace

### PR DESCRIPTION
**Pull request by lslatr**
This PR adds RouteReplace which is RouteAdd with the flag NLM_F_REPLACE instead of NLM_F_EXCL for RouteAdd

### CODE REVIEW

**Comment by lslatr** [comment]
This is a simple API add... I think the Makefile is messed up and is causing the automated tests to fail.

**Comment by vishvananda** [comment]
The makefile is fine. You have a formatting issue. Try running go fmt on your file and resubmitting. Also, it is worth adding a simple test for it.  You can copy the TestRouteAddDel and modify it.

**Comment by lslatr** [comment]
Got it... I'm a go newbie.  I'll add a test.

**Comment by lslatr** [comment]
@vishvananda ok added a ReplaceRoute test... think we're good to go.

**Pull request merged**
