### PR TITLE
Add bridge dump support

### PR DESCRIPTION
**Pull request by diconico07**
This PR add support for bridge neigh entries dump on subscribe and also add a bridge related attribute to neigh structure

### CODE REVIEW

**Comment by diconico07** [comment]
Added support of MasterIndex in neighHandle() as I forgot it at first.

**Comment by vishvananda** [comment]
The code here looks correct. Is it possible to create a test to validate that it is working properly?

**Comment by diconico07** [comment]
I had to change a bit more than I thought for the tests. The only disappointing thing is the need for a vxlan interface in the test as the FDB entries for vxlan interfaces are really close to usual neigh entries and can thus be checked using the same function in the tests.

**Comment by diconico07** [comment]
Anything else needed from me ?

**Comment by aboch** [comment]
Please squash your commits into one

**Comment by aboch** [comment]
LGTM

**Pull request merged**
