### PR TITLE
windows: Fix compilation issue

### LINKED ISSUE #146: Build failure for windows binaries
Just pulled the latest, and get this when I try to build a windows binary:

```
vendor/github.com/vishvananda/netlink/xfrm.go:12: undefined: syscall.IPPROTO_ROUTING
vendor/github.com/vishvananda/netlink/xfrm.go:13: undefined: syscall.IPPROTO_ESP
vendor/github.com/vishvananda/netlink/xfrm.go:14: undefined: syscall.IPPROTO_AH
vendor/github.com/vishvananda/netlink/xfrm.go:15: undefined: syscall.IPPROTO_DSTOPTS
vendor/github.com/vishvananda/netlink/xfrm.go:17: undefined: syscall.IPPROTO_RAW
```

### PR DESCRIPTION
**Pull request by sayboras**
This commit is to make sure there is no compilication issue
with windows.

Fixes #146

Signed-off-by: Tam Mach <sayboras@yahoo.com>

### CODE REVIEW

**Review by tklauser — COMMENTED** [review]
I think instead of hard-coding these constants we could also just rename `xfrm.go` to `xfrm_linux.go` since this functionality only applies to Linux anyway.

**Comment by aboch** [comment]
> I think instead of hard-coding these constants we could also just rename `xfrm.go` to `xfrm_linux.go` since this functionality only applies to Linux anyway.

I second that. I do not see a point in making this very linux specific library code compile smoothly on Windows.
Can you instead try to stub the code for Windows or rename the file to make it linux specific ?

**Comment by sayboras** [comment]
thanks both, let me adjust the changes.

**Comment by lucheng0127** [comment]
@tklauser Hi, I'm still got this problem, when I use github.com/vishvananda/netlink v1.1.0
Does this patch available in pkg.go.dev?
The latest netlink version is v1.1.0 and published on 2020-01-17

**Pull request closed without merging**
