### PR TITLE
Use tristate(negative/0/positive) fields for Protinfo

### PR DESCRIPTION
**Pull request by LK4D4**
I noticed that it is not very convenient to use default bool value,
because IFLA_PROTINFO fields is not always false by default.

### CODE REVIEW

**Comment by vishvananda** [comment]
I don't love the -1s representing not set. It seems like it would be more accurate to use *bool and leave them null if they are not set. Thoughts?

**Comment by LK4D4** [comment]
@vishvananda Maybe you're right that -1 is not cool, but pointers is not very convenient to use. Then we probably need make setters and getters for each field. Or I can create tristate type with `Unset, Yes, No` values or something like this. What do you think?

**Comment by LK4D4** [comment]
Now I think that setters/getters + MarshalJSON method maybe not bad option. Let me know your opinion about that.

**Comment by vishvananda** [comment]
how about something like a specialized type like:

https://code.google.com/p/go/source/browse/cmd/vet/main.go?repo=tools#53

**Comment by LK4D4** [comment]
@vishvananda Seems like not convenient to use, compare
```
protinfo.Hairpin = netlink.PROTINFO_TRUE
protinfo.Hairpin = netlink.PROTINFO_FALSE
protinfo.Hairpin = netlnik.PROTINFO_UNSET
```
with
```
protinfo.SetHairpin(true)
protinfo.SetHairpin(false)
protinfo.UnsetHairpin()
```

**Comment by vishvananda** [comment]
the issue with setters is that none of the other fields have Setters and it is confusing that link.SetMTU(9000) actually makes a netlink call to set the mtu whereas protinfo.SetHairpin(true) would just be setting the field. Maybe what we really want is a command on link for each of the fields:

link.GetHairpin() *bool (or tristate)
link.SetHairpin(true)
link.SetHairpin(false)
...

rather than link.SetProtInfo/link.GetProtInfo

**Comment by LK4D4** [comment]
@vishvananda Maybe you're right, personally for my case I don't care about +-3 calls to netlink for setting multiple fields in Protinfo. I'll open another PR about that. Should simplify interface for user. Problem only that getting that attributes will be different from for example `MTU` anyway :(

**Pull request closed without merging**
