### PR TITLE
Fix build error

### PR DESCRIPTION
**Pull request by krhubert**
How this happend that CI dosen't catch build error?

### CODE REVIEW

**Comment by rade** [comment]
> How this happend that CI dosen't catch build error?

Looks like the CI is configured to simply run 'make'. And the default target in the Makefile... just runs `gofmt`.

**Comment by andrewtchin** [comment]
+1 please merge this

**Comment by vishvananda** [comment]
yeah unfortunately the tests require sudo so they don't really work on the ci server. I should at least modify it to do some kind of sanity build.

**Comment by chantra** [comment]
Re ci, there is way to run as root when using vms. You may need to use the trusty image to get a kernel that is somehow newish.

**Comment by LK4D4** [comment]
Also, it's possible with `unshare -Urn`, but you need newer util-linux.

**Comment by vishvananda** [comment]
FYI i got the tests running in travis. I had to skip the ipvlan tests because the kernel is too old. Also there is a failure in the addr_linux tests. It looks like the older kernel doesn't set IFA_F_PERMANENT on the loopback device?

**Pull request merged**
