### PR TITLE
netkit: Add support for IFLA_NETKIT_SCRUB and IFLA_NETKIT_PEER_SCRUB

### PR DESCRIPTION
**Pull request by jrife**
A recent [patch series](https://lore.kernel.org/netdev/8c763b0e-743c-4f10-a497-8ede27eefe26@blackwall.org/T/#t) adds support for two new netkit flags, `IFLA_NETKIT_SCRUB` and `IFLA_NETKIT_PEER_SCRUB`, allowing configuration of the the packet scrubbing behavior for the primary and peer device, respectively. This PR adds support for these new flags. As a follow up, this PR will be used to implement [this fix](https://github.com/cilium/cilium/pull/35306) in Cilium.

### CODE REVIEW

**Comment by jrife** [comment]
cc @borkmann

**Review by borkmann — APPROVED** [review]

**Comment by borkmann** [comment]
Hi 👋 @aboch, if you get a chance, please take a look. :)

**Comment by aboch** [comment]
Sure this will go in.
Am I seeing correctly that the referenced addition to Linux is not even in the latest [6.13-rc](https://github.com/torvalds/linux/blob/v6.12-rc3/tools/include/uapi/linux/if_link.h)?

**Comment by borkmann** [comment]
> Sure this will go in. Am I seeing correctly that the referenced addition to Linux is not even in the latest [6.13-rc](https://github.com/torvalds/linux/blob/v6.12-rc3/tools/include/uapi/linux/if_link.h#L772)?

This is going into 6.13, not 6.12, but I expect stable to pick this up as well.

**Review by tklauser — APPROVED** [review]

**Comment by borkmann** [comment]
@aboch Have a chance to merge if it looks good to you? (It's blocking a few important Cilium fixes in relation to netkit). Thanks so much for your help.

**Comment by jrife** [comment]
Just to follow up, I'm also curious what the release cadence is? We can potentially pin `go.mod` to a specific commit in Cilium once this is merged, but it would be nice to be pinned to a release tag.

**Pull request merged**
