### PR TITLE
rule: add support for ipproto

### PR DESCRIPTION
**Pull request by MrHohn**
This is similar to https://github.com/vishvananda/netlink/pull/511, but this time for the `ipproto` option:
```
ip rule add ipproto xxx table main
```

### CODE REVIEW

**Comment by aboch** [comment]
pls rebase and force push so that CI (now fixed) will be triggered

**Comment by MrHohn** [comment]
> pls rebase and force push so that CI (now fixed) will be triggered

Thanks, done now.

**Comment by MrHohn** [comment]
Humm, the CI is still failing. Let me rebase again.

**Comment by MrHohn** [comment]
> Humm, the CI is still failing. Let me rebase again.

Rebased.

**Comment by vishvananda** [comment]
Don't you also need to retrieve the value and set it when parsing the message? Could you add that and also check to make sure the value is set properly in the test?

**Comment by glazychev-art** [comment]
Hello @MrHohn ,
Are there any updates? We are also interested in this PR
Thanks

**Pull request closed without merging**
