### PR TITLE
initial IPSet support

### PR DESCRIPTION
**Pull request by onokonem**

### CODE REVIEW

**Comment by aboch** [comment]
@onokonem, given #387 was already there, can you please sync with @corny to avoid duplicate code proposal. (I have not looked at the two PR in detail yet, if there is no overlap then we are good)

**Comment by aboch** [comment]
@onokonem @corny 
Regarding the ipset support where we are ending up with the duplicated proposals issue.
I discussed with @vishvananda and @fcrisciani: We are proposing the following transitions:
1) @onokonem leads the transition changes (based on his continuous activity on this area)
2) @onokonem rearranges his initial ipset support PR (#408) changes to be incremental work on top of @corny 's commits  (based on @corny's PR came in first). 
3) @onokonem retains @corny's authored commit (the squash of his 7 commits from #387) in the new PR.
4) The new PR must have two commits: One from @corny and one from @onokonem 
4) close #387 and #408 when above is done



Thank you.

**Comment by jellonek** [comment]
Can you rebase that on top of current master?

**Comment by jellonek** [comment]
Ups. This one has to be closed...

**Comment by onokonem** [comment]
of course I can rebase this on top of current master

we are using this functionality so we would be happy to get this merged to the upstream

**Comment by onokonem** [comment]
> @onokonem @corny
> Regarding the ipset support where we are ending up with the duplicated proposals issue.
> I discussed with @vishvananda and @fcrisciani: We are proposing the following transitions:
> 
>     1. @onokonem leads the transition changes (based on his continuous activity on this area)
> 
>     2. @onokonem rearranges his initial ipset support PR (#408) changes to be incremental work on top of @corny 's commits  (based on @corny's PR came in first).
> 
>     3. @onokonem retains @corny's authored commit (the squash of his 7 commits from #387) in the new PR.
> 
>     4. The new PR must have two commits: One from @corny and one from @onokonem
> 
>     5. close #387 and #408 when above is done
> 
> 
> Thank you.

for the reason I do not fully understand I did not saw this comment before

yes this sounds like a plan

I'm working on some addition to the ipset support right now on our side so I'll take the steps proposed as part of this activity.

**Comment by jellonek** [comment]
Tests show that rebase was probably not successful.

**Pull request closed without merging**
