### PR TITLE
Support num{tx,rx}queues and udp6zerocsum{tx,rx}

### PR DESCRIPTION
**Pull request by s1061123**
Add IFLA_NUM_TX_QUEUES and IFLA_NUM_RX_QUEUES in link attribute and
IFLA_VXLAN_UDP_ZERO_CSUM6_TX and IFLA_VXLAN_UDP_ZERO_CSUM6_RX in VXLAN
attribute.

### CODE REVIEW

**Comment by vishvananda** [comment]
This looks correct. I think you also need to parse the values during link list? A test would also be helpful to ensure that the values are getting set correctly.

**Comment by s1061123** [comment]
Thank you for your review! Let me add parase and test and update it.

**Comment by s1061123** [comment]
In my host, TestLinkAddDelVxlan is passed, but TravisCI makes it failed and now I am troubleshooting on it.

> === RUN   TestLinkAddDelVxlan
> --- PASS: TestLinkAddDelVxlan (0.03s)

**Comment by aboch** [comment]
@s1061123 Please rebase to latest, resolve the conflict, squash the commits in one and add the `minKernelRequired(t, N, M)` call before the new tests, as I see `IFLA_VXLAN_UDP_ZERO_CSUM6_TX` is not present in kernel 3.10 for example. Maybe add a dedicated test function for `IFLA_VXLAN_UDP_ZERO_CSUM6_TX/RX` flags so that only will be skipped on older kernels.

**Comment by s1061123** [comment]
Thank you for your info, @aboch !
I will do that in a few days.

**Comment by s1061123** [comment]
Update the diffs.

**Comment by aboch** [comment]
@s1061123 Please rebase again and squash the commits into one before pushing.

**Comment by s1061123** [comment]
@aboch thank you for your advice! I've squashed into one commit.

**Comment by aboch** [comment]
Thank you @s1061123. LGTM

**Pull request merged**
