### PR TITLE
Fix: Proper parsing of mark

### PR DESCRIPTION
**Pull request by sibicramesh**
--> This PR fixes the bug that breaks the parsing

`udp	17 src=127.0.0.1 dst=127.0.0.10 sport=2003 dport=3000 packets=0 bytes=0	src=127.0.0.10 dst=127.0.0.1 sport=3000 dport=2003 packets=0 bytes=0 mark=0`

### CODE REVIEW

**Comment by fcrisciani** [comment]
@sibicramesh can you keep the original indentation so to minimize the diff?

**Comment by fcrisciani** [comment]
can you also add a test, so that we avoid further regressions?

**Comment by aboch** [comment]
@sibicramesh Please also squash your commits in one after you fix the formatting
`gofmt *.go`

**Comment by aboch** [comment]
Closing for inactivity.

**Pull request closed without merging**
