### PR TITLE
`Rule.String()` method returns `.Dst`

### PR DESCRIPTION
**Pull request by qdm12**
- Return `to <all | ipNetString>` in string
- Return `all` for `from` if `rule.Src == nil`
- Return `all` for `to` if `rule.Dst == nil`

### CODE REVIEW

**Comment by aboch** [comment]
pls rebase and force push so that CI (now fixed) will be triggered

**Comment by aboch** [comment]
Please squash your commits into one then force push. (This repo does not have "Squash-Merge" option)

**Comment by qdm12** [comment]
> Please squash your commits into one then force push.

Done 😉

> This repo does not have "Squash-Merge" option enabled

Why not out of curiosity 🤔 ?

**Comment by aboch** [comment]
>Why not out of curiosity thinking ?

It was like this since I came around here.

I think Vish wanted to have a clear 1-to-1 mapping between commit and PR. Which I also like.

**Pull request merged**
