### PR TITLE
Support XFRMA_REPLAY_VAL attribute

### PR DESCRIPTION
**Pull request by YutaroHayakawa**
This PR has a conflict with https://github.com/vishvananda/netlink/pull/765, so built on top of it. Please review it first, then I'll rebase this branch once it is merged.

### CODE REVIEW

**Comment by tklauser** [comment]
> TestLinkAddDelXfrmiNoId is failing, but this is not related to the changes. Looks like it is failing in other PRs as well (e.g. https://github.com/vishvananda/netlink/runs/6273054919?check_suite_focus=true).

Rebasing on top of latest `main` should fix the test failure.

**Review by tklauser — APPROVED** [review]
LGTM

/cc @vishvananda @aboch could you PTAL?

**Comment by YutaroHayakawa** [comment]
Rebased to the latest master and all tests are passing now.

@aboch As I mentioned in the PR message, the second commit conflicts (depends) on the first commit which is introduced in https://github.com/vishvananda/netlink/pull/765. When https://github.com/vishvananda/netlink/pull/765 merged, I'll rebase this branch with master, then the first commit will disappear.

**Comment by aboch** [comment]
Please rebase

**Comment by YutaroHayakawa** [comment]
Rebased

**Comment by aboch** [comment]
LGTM

**Pull request merged**
