### PR TITLE
support netkit

### PR DESCRIPTION
**Pull request by chent1996**
this PR add support to manage a netkit device in Golang

authored-by: tangchen <tangchen.1@bytedance.com>

### CODE REVIEW

**Comment by chent1996** [comment]
This netkit device was merged to Linux upstream by @borkmann 

https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=22360fad5889cbefe1eca695b0cc0273ab280b56

**Review by borkmann — APPROVED** [review]
Looks great, thanks for working on this!

**Comment by borkmann** [comment]
Cc @aboch :wave:

**Review by NikAleksandrov — APPROVED** [review]
Looks good!

**Comment by aboch** [comment]
LGTM

**Pull request merged**
