### PR TITLE
Add support for TCA_NETEM_RATE64 in Netem qdisc

### PR DESCRIPTION
**Pull request by bc-lee**
- `Rate64` field added to the `Netem` struct in `qdisc.go`
- Implemented serialization and deserialization methods for `Rate64`
- Modify `TestClassAddDel` test to validate Rate64 changes

### CODE REVIEW

**Comment by aboch** [comment]
@bc-lee

**Comment by aboch** [comment]
@bc-lee please fix the conflicts and can you add some UT?

**Comment by bc-lee** [comment]
> @bc-lee please fix the conflicts and can you add some UT?

Sorry for the delay. I have fixed the conflicts and modify existing test(`TestClassAddDel`) to validate Rate64 changes. Can you please take a look at it?

**Comment by aboch** [comment]
LGTM

**Pull request merged**
