### PR TITLE
Add IifIndex option to RouteGetOptions

### PR DESCRIPTION
**Pull request by hmahmood**
This is helpful (especially in our codebase), where we already know the link index, and avoids an extra call to netlink.

### CODE REVIEW

**Comment by hmahmood** [comment]
@aboch @vishvananda hello, would appreciate a review of this, thanks.

**Comment by hmahmood** [comment]
Could someone review this PR please? @aboch maybe? It has been sitting in review for quite some time.

**Comment by aboch** [comment]
Thanks @hmahmood 
Can you please extend existing RouteGet UT (if any) to make program and read back a route with ifindex?

**Comment by hmahmood** [comment]
@aboch added a test.

**Comment by aboch** [comment]
Please have only one commit per feature/addition/bug fix

Looks to me you have a commit for adding an option to the routeget method and one bug fix for the routeget method.
So these two can come separate in two distinct commits.
The UT commit instead must be squashed into the first commit.

**Comment by hmahmood** [comment]
@aboch done

**Comment by aboch** [comment]
LGTM

**Pull request merged**
