### PR TITLE
fix link attribute *NetNsID*

### PR DESCRIPTION
**Pull request by zhangzujian**
This PR fix issue #478.

### CODE REVIEW

**Comment by vishvananda** [comment]
I think i prefer leaving this as an int and using -1. Otherwise we may be breaking code that is in use.

**Comment by aboch** [comment]
@zhangzujian Please address the comment

**Comment by jellonek** [comment]
@zhangzujian ping

**Comment by aboch** [comment]
@zhangzujian ping

**Comment by zhangzujian** [comment]
So sorry for the delay.

I totally understand and respect vishvananda's opinion while I insist a pointer is better and will NOT change my code. Should I close this PR so that another guy can create a new one and fix the issue?

**Comment by lebauce** [comment]
I pushed the following PR to use default values for NetNSID : https://github.com/vishvananda/netlink/pull/562

**Pull request closed without merging**
