### PR TITLE
Support IPv6 GRE Tun and Tap

### LINKED ISSUE #316: IPv6 address not handled properly for Gretun
In iproute2, IPv6 GRE tunnels are called "ip6gre"'s. The current implementation will result in mysterious "file exists" errors when trying to add a Gretun object.

### PR DESCRIPTION
**Pull request by aboch**
Fixes #316 

Also the changes allow to re-enable `TestLinkAddDelGretapFlowBased`

### CODE REVIEW

**Comment by aboch** [comment]
ping @KireinaHoro Please give it a try too.

**Comment by KireinaHoro** [comment]
The link-add part works now. I'm trying to find a way to add an address to the link and bring it up though...

**Comment by KireinaHoro** [comment]
Seems like it's working fine. I've tested with the following:

```go
package main

import (
    "github.com/aboch/netlink"
    "log"
    "net"
    "fmt"
)

func main() {
    la := netlink.NewLinkAttrs()
    la.Name = "foobar"

    l, err := netlink.LinkByName(la.Name)
    if err == nil {
        log.Fatalf("Link with name \"%s\" already exists", la.Name)
    }
    myGretun := &netlink.Gretun{LinkAttrs: la}
    myGretun.Remote = net.ParseIP("2001:da8::1")
    myGretun.Local = net.ParseIP("2001:da8::2")
    err = netlink.LinkAdd(myGretun)
    if err != nil {
        log.Fatalf("Could not add %s: %v", la.Name, err)
    }
    l = myGretun
    addr, err := netlink.ParseAddr("172.16.0.1/32")
    if err != nil {
        netlink.LinkDel(myGretun)
        log.Fatalf("Failed to parse address: %v", err)
    }
    netlink.AddrAdd(l, addr)
    netlink.LinkSetUp(l)
    fmt.Printf("Information about the created link: %v", l)
}
```

**Comment by aboch** [comment]
Thanks @KireinaHoro

**Pull request merged**
