### PR TITLE
Retrieve VLAN ID when listing neighbour

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by vishvananda** [comment]
Thanks for the patch. I generally try to use int for values in the netlink library and convert back and forth when parsing. Would you mind switching vlan to an int?

**Comment by lebauce** [comment]
@vishvananda Sorry, I completely missed the notification. I rebased, added VNI and addressed your remark

**Comment by aboch** [comment]
@lebauce Please rebase

**Comment by aboch** [comment]
@lebauce Please rebase

**Comment by lebauce** [comment]
@aboch Done

**Comment by aboch** [comment]
Thank @lebauce

**Pull request merged**
