### PR TITLE
Add support for TC_ACT_CONNMARK

### PR DESCRIPTION
**Pull request by kmjohansen**
Implements the connmark action described in tc-connmark(8)

Signed-off-by: Krister Johansen <krister.johansen@oracle.com>

### CODE REVIEW

**Comment by vishvananda** [comment]
This looks good to me. I'll leave it for a bit to see if anyone else has comments

**Comment by kmjohansen** [comment]
Thanks; appreciate the speedy review.  For posterity, a few connmark related links that I probably should have included in the synopsis:

The manpage: http://man7.org/linux/man-pages/man8/tc-connmark.8.html
The linux headers: https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/tc_act/tc_connmark.h#L10
The action's implementation in kernel: https://elixir.bootlin.com/linux/latest/source/net/sched/act_connmark.c

Fun fact about the bookkeeping in `act_connmark.c`: the implementation uses the `overlimits` statistic to record when it copies a mark onto a packet.

**Comment by kmjohansen** [comment]
There hasn't been any further discussion in the last week.  Are you ok to merge this, @vishvananda?

**Comment by kmjohansen** [comment]
@vishvananda Is there anything outstanding that needs to be resolved here?  If not, may I trouble you to merge these changes, please?

**Comment by aboch** [comment]
LGTM

**Comment by kmjohansen** [comment]
Thanks, guys

**Comment by vishvananda** [comment]
It appears that a couple of tests are consistently failing since this merged:
```=== RUN   TestClassAddDel
--- FAIL: TestClassAddDel (0.16s)
	class_test.go:110: Failed to add class
=== RUN   TestHtbClassAddHtbClassChangeDel
--- FAIL: TestHtbClassAddHtbClassChangeDel (0.01s)
	class_test.go:342: 1 class expected, 2 found```

**Comment by kmjohansen** [comment]
My apologies if I've broken anything here.  The tests had been passing for me prior to integration.
Is it possible for stale state to get left behind in the test harness from failed runs?  I ask because the test function I added `TestFilterU32ConnmarkAddDel()` doesn't explicitly create any classes -- just qdisc, filter, and actions.  It follows the same pattern as other tests in that module for cleanup.  Namely, it deletes the filter with the attached action, and then deletes the qdisc.

**Comment by vishvananda** [comment]
Turns out it was due to unrelated updates of the kernel, so you don't need
to change anything

**Pull request merged**
