### PR TITLE
Fix NewHtbClass

### PR DESCRIPTION
**Pull request by chenchun**
- Prio and Quantum should be set equal to the input params
- Fix buffer and cbuffer due to incorrect hz

### CODE REVIEW

**Comment by chenchun** [comment]
Fixes https://github.com/vishvananda/netlink/issues/560

**Comment by chenchun** [comment]
Add a second commit to fix Xmittime which is also not equal the behavior of c library. C library converts time to uint32 to drop precision before multiply tick_in_usec. ref https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/tc/tc_core.c#n62

**Comment by vishvananda** [comment]
this lgtm, but can you squash it into commit please?

**Comment by chenchun** [comment]
done

**Pull request merged**
