### PR TITLE
Conntrack support

### PR DESCRIPTION
**Pull request by fcrisciani**
These 2 commits are introducing the support for netfilter conntrack into the library.
This PR is a dependency for the fix of the bug: https://github.com/docker/docker/issues/8795

The first commit adds the logic to support the GET/FLUSH/DELETE of conntrack through netlink
The second commit adds a test on top

### CODE REVIEW

**Comment by fcrisciani** [comment]
Looks like I will have to investigate the failure on Travis. 
Was thinking was missing netcat but with my last commit the test should had been skip

**Comment by fcrisciani** [comment]
The issue was the missing modules in the kernel, added them into Travis file.

**Comment by vishvananda** [comment]
This looks good. I'm thinking we may need a conntrack_unspecified.go with NotImplemented calls so that projects build on non-linux environments?

**Comment by fcrisciani** [comment]
Sure, let me take care of that

**Pull request merged**
