### PR TITLE
Add devlink command to query common devlink port attributes

### PR DESCRIPTION
**Pull request by paravmellanox**
Devlink ports has several common attributes typically exposed by an eswitch devlink device.

Add devlink commands to query devlink port list and query specific devlink port attributes.
Added unit tests for both the new APIs.

### CODE REVIEW

**Comment by vishvananda** [comment]
Can you squash this into a single commit please?

**Comment by paravmellanox** [comment]
@vishvananda ok. will do. Thanks.

**Comment by paravmellanox** [comment]
@vishvananda I had more attributes and was waiting for this merge, but since I am resending, I as well merge rest of them too.

**Comment by aboch** [comment]
LGTM

**Pull request merged**
