### PR TITLE
netlink: xfrm, add optional field to XfrmPolicyTmpl

### PR DESCRIPTION
**Pull request by joestringer**
Add optional field in XfrmPolicyTmpl to template code so users can
configure template optional values.

### CODE REVIEW

**Comment by aboch** [comment]
is it possible to add or extend current UT to verify this information was passed down to kernel, for ex write it and read it back?

**Comment by joestringer** [comment]
@aboch :+1: good call, the deserialization was missing. I've added a test and it passes:

        $ go test -exec sudo . -run XfrmPolicyWithOptional
        ok      github.com/vishvananda/netlink  0.009s

**Comment by joestringer** [comment]
@aboch any update, does the new version look OK?

**Comment by aboch** [comment]
LGTM

**Pull request merged**
