### PR TITLE
devlink port add, delete, function get/set attributes

### PR DESCRIPTION
**Pull request by paravmellanox**
This patchset consist of 3 main functionalities.

1. Shows optional devlink port function attributes when filled by kernel
2. Add APIs to add devlink port by specifying device identification, port flavour and port attributes
3. Port function attributes set

Patchset contains relevant test cases as well with a ability to specify device handle at command line.

### CODE REVIEW

**Comment by paravmellanox** [comment]
@vishvananda,

Can you please review? Want to proceed to use in a new cni plugin.

**Comment by paravmellanox** [comment]
Hi @vishvananda,

Gentle remind. If we can proceed with this enhancement.

**Comment by paravmellanox** [comment]
@vishvananda @aboch 

Did you get a chance to review it? Can we please proceed?

**Comment by paravmellanox** [comment]
@vishvananda @aboch 
ping.

**Comment by aboch** [comment]
pls push something so that the CI runs

**Comment by paravmellanox** [comment]
@aboch, thanks for the input. I pushed again after rebase. All checks pass.

**Pull request merged**
