### PR TITLE
Add bond slave information

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by lebauce** [comment]
@vishvananda Can you please take a look ? Thanks !

**Comment by vishvananda** [comment]
This code looks correct, but it would be great to have a test for it. Is it possible to add a bond slave already? If so, a test should be straightforward. If not, then that is probably functionality we need as well.

**Comment by aboch** [comment]
ping @lebauce

**Comment by aboch** [comment]
Sorry, no feedback for the past 5 months. Will go with #487

**Comment by lebauce** [comment]
@aboch Sorry, missed the notifications. Thanks for finishing my work :-)

**Pull request closed without merging**
