### PR TITLE
Add AddrAddWithoutCalculatedBroadcast

### LINKED ISSUE #471: Broadcast address added to device while not explicitly requested
When I call AddrAdd(link, addr), the library currently automatically adds a broadcast address:
https://github.com/vishvananda/netlink/blob/master/addr_linux.go#L110

This can become problematic when we are using a /31 for p2p links. For example in our use case we have a GRE tunnel. If we want to assign e.g. 10.128.0.2/31 to one side, and then try to use 10.128.0.3 as gateway to route to remote tunnel, then it will report invalid gateway.

Can we have an option to not by default add brd address?

### PR DESCRIPTION
**Pull request by jellonek**
Added as a separate func to not introduce an API breaking change.
Closes #471

### CODE REVIEW

**Comment by jellonek** [comment]
@vishvananda @aboch @fcrisciani PTAL
I still thing that this should be done as a breaking API change, that broadcast calculated address should be added only when requested as an option, but that would require a new release of whole library.
WDYT?

**Comment by jerryz920** [comment]
Thanks for the PR! Do you have other concerns to merge and release this one @vishvananda ?

**Comment by aboch** [comment]
IMO, I believe it is worth investigating other approaches, trying hard to avoid adding such a specific method.

**Comment by jerryz920** [comment]
Without adding new method then it will definitely cause API semantic change. Will it make sense to not automatically add brd address on /31 or /30?

**Comment by jellonek** [comment]
IMO it makes sense, but that would be breaking change. That's why I'm asking there also @vishvananda

**Comment by jellonek** [comment]
@vishvananda ping

**Comment by brandt** [comment]
@aboch @jellonek I just submitted PR #496 with a different approach mirroring @dannyk81's suggestion in #329 to no longer automatically set the broadcast address on subnets too small to logically have one (/32 and /31).

As I mention in #496, another alternative – one that already works today – is to set the broadcast address to `net.IP{0, 0, 0, 0}`. However, I don't presently know if that's part of netlink's public API or if it's a quirk that could break in the future.

**Comment by dannyk81** [comment]
thanks @brandt, at the time I was meaning to do a similar PR and... life got the best of me :sweat_smile:

**Comment by vishvananda** [comment]
I went ahead and merged the non-breaking change so going to close this for now. Please rebase and reopen if you think that we should also have this method.

**Pull request closed without merging**
