### PR TITLE
fixing issue with setting big endian

### PR DESCRIPTION
**Pull request by brahmaroutu**
Signed-off-by: Srini Brahmaroutu <srbrahma@us.ibm.com>

### CODE REVIEW

**Comment by vishvananda** [comment]
Can you explain what the deal is here? Is the Big Endian handling completely unnecessary? should we remove it altogether?

**Comment by brahmaroutu** [comment]
@vishvananda Without the else block it is never set to Big Endian when testing Docker on IBM Z. This change is helping me to set to that value.

**Comment by vishvananda** [comment]
Is the ibmz big endian? If so I'm thinking that the big endian code is
unnecessary and we should just remove all the endianness checks.

**Comment by brahmaroutu** [comment]
yep I need to support big endian. I am trying to follow why you did not want to use else block? Not sure why we need endian check, I do not know this code well enough to comment. For sure the code is not working on IBM Z without setting it.

**Comment by brahmaroutu** [comment]
@vishvananda I hope you can merge this PR, we need this for Docker work on Z. Please let me know if you see any issues.

**Comment by brahmaroutu** [comment]
Thanks for merging this PR

**Pull request merged**
