### PR TITLE
Add support for output-mark

### PR DESCRIPTION
**Pull request by lbernail**
Support for output-mark in xfrm states
I tried to have an implementation very close to the iproute one

I have tested it and had no problem with it but I may still have forgotten something. More than happy to update the PR if this is the case

### CODE REVIEW

**Comment by aboch** [comment]
Please extend the existing xrfm_state UT to also exercise the writing/reading of this field

**Comment by lbernail** [comment]
@aboch sure, I'll do this as soon as I can

**Comment by lbernail** [comment]
@aboch : I added a test (only applies to kernels that support the feature: 4.14+)
I created a commit for the unit test, I can squash into the main one if it makes more sense

**Comment by aboch** [comment]
Thanks.
Yes please, this project follows a "one commit per PR/topic" approach.

**Comment by lbernail** [comment]
@aboch Thanks! I just squashed the commits

**Comment by aboch** [comment]
LGTM

**Comment by lbernail** [comment]
Thanks!

**Pull request merged**
