### PR TITLE
Add support for managing source MACVLANs

### PR DESCRIPTION
**Pull request by lukegb**
Add MacvlanMACAddrAdd, MacvlanMACAddrDel, MacvlanMACAddrSet and MacvlanMACAddrFlush for managing the MAC addresses associated with a `source`-type macvlan interface.

Populates a `MACAddrs` field on Macvlan if the information is provided by Netlink.

### CODE REVIEW

**Comment by vishvananda** [comment]
This looks reasonable. Is there a reason it is still marked WIP?

**Comment by aboch** [comment]
ping @lukegb 

Is it still WIP ?

**Comment by lukegb** [comment]
This should work - I'm not using it anymore myself, but it should be good to go.

**Comment by aboch** [comment]
Thanks @lukegb. Please replace `syscall` with `unix` pkg and sign your commit.

**Comment by aboch** [comment]
@lukegb. Please replace syscall with unix pkg (See #286) and sign your commit.

**Comment by aboch** [comment]
Thanks @lukegb I carried over your commit + requested changes in #303

**Pull request closed without merging**
