### PR TITLE
Make IPSet actually support hash set types

### PR DESCRIPTION
**Pull request by lrh3321**
- support hash set types:
  - `hash:ip`
  - `hash:ip,mac`
  - `hash:ip,mark`
  - `hash:ip,port`
  - `hash:ip,port,ip`
  - `hash:ip,port,net`
  - `hash:net`
  - `hash:net,iface`
  - `hash:net,net`
  - `hash:net,port`
  - `hash:net,port,net`
- add support for `bitmap:port` set type

### CODE REVIEW

**Comment by lrh3321** [comment]
@aboch how about this PR

**Comment by aboch** [comment]
Please squash your two commits into one, or have one PR per commit.
Also please push again so CI starts

**Comment by aboch** [comment]
pls rebase and force push so that CI (now fixed) will be triggered

**Comment by aboch** [comment]
LGTM

**Pull request merged**
