### PR TITLE
add vti6 support

### PR DESCRIPTION
**Pull request by semicomplete**

### CODE REVIEW

**Comment by aboch** [comment]
LGTM

**Comment by fcrisciani** [comment]
@semicomplete can you sign the commit?
`git commit --amend -s`

**Comment by semicomplete** [comment]
Done.

**Comment by fcrisciani** [comment]
@semicomplete thanks

**Comment by semicomplete** [comment]
@fcrisciani, @aboch actually, thank you, guys, for maintaining the library :+1:

**Pull request merged**
