### PR TITLE
Add support for additional TC BPF filter attributes

### PR DESCRIPTION
**Pull request by fzakaria**
In order to support BPF_SYSCALL `PROG_GET_FD_BY_ID` -- the ID of the
eBPF must be available. Add the additional enumerations and handle them when parsing the BPF
filter.

When running it on a loaded direct-action eBPF TC filter I only saw the following returned:
TCA_BPF_NAME, TCA_BPF_ID, TCA_BPF_TAG, TCA_BPF_FLAGS, TCA_BPF_FLAGS_GEN

### CODE REVIEW

**Comment by vishvananda** [comment]
This looks correct, but I think the new attributes need to be added to the FilterAdd section as well.

**Comment by fzakaria** [comment]
@vishvananda I don't think you set the tag or the id
So should only be on the retrieval.

bpf_prog_calc_tag - https://elixir.bootlin.com/linux/v4.14/source/kernel/bpf/core.c#L152
bpf_prog_alloc_id- https://elixir.bootlin.com/linux/v4.20.17/source/kernel/bpf/syscall.c#L1165

**Comment by fzakaria** [comment]
@aboch can you merge this ?
I see you're a new active maintainer on this project.

**Comment by aboch** [comment]
Looks like question was responded. Merging then.

LGTM

**Comment by fzakaria** [comment]
@aboch  thanks --
What's the plan for tags/releases -- for go modules.

**Pull request merged**
