### PR TITLE
added encapsulation attributes for Iptun and Sittun to support SIT tunnels

### PR DESCRIPTION
**Pull request by skoef**
The `Iptun` struct didn't support encapsulation attributes like source or destination port yet, while `Gretap` did and the feature appeared for both interface types around the same time. I basically copied the parsing and adding of the attributes from `Gretap` to `Iptun` and it seems to work fine.

### CODE REVIEW

**Comment by skoef** [comment]
For this project I'm doing I would like SIT tunnel support in this library as well. Since these links are similar to `Iptun` I could ofcourse copy/paste relevant functions and type of `Iptun` but I'm not sure that is the way to go here

**Comment by vishvananda** [comment]
This looks reasonable. Can you squash it down into a single commit?

Thanks

**Comment by skoef** [comment]
I thought github featured a squash&merge button, nevertheless: it's squashed, no problem!

**Comment by vishvananda** [comment]
it does support squash and merge, but I prefer rebase and merge to keep a linear commit tree. :)

**Pull request merged**
